import:
 source: ./tests/travis/setup-php.yml

script:
 - composer install --prefer-dist
 - composer update
 - ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
 - composer install --no-dev --prefer-dist
 - composer update
 - ./tests/travis.sh -t4

cache:
 directories:
  - $HOME/.composer/cache/files
  - $HOME/.composer/cache/vcs

notifications:
 email:
  recipients:
   - dtcu0ng@dtcg.xyz
  on_success: change
  on_failure: always
